version: "3.8"

services:
  web:
    build: ./web
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to start...' &&
        sleep 10 &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

